### ISSUE TITLE
danmu.jar的】

### ISSUE THREAD

**Issue by ne7359** [PizazzGY/TVBox#15]
danmu.jar 可能有问题，很多使用danmu.jar的都无法加载

**Comment by ne7359** [comment]
danmu.jar 可能有问题，很多使用danmu.jar的都无法加载

                                                                          望能修复谢谢

**Comment by PizazzGY** [comment]
> danmu.jar 可能有问题，很多使用danmu.jar的都无法加载

能正常加载啊，没发现什么问题
